steps:
  - label: ":docker: Build docker image"
    command: "cd hello && go build -o ./dist/hello ."
    artifact_paths: "./hello/dist/hello"
    plugins:
      - docker#v5.12.0:
          image: "golang:1.15"
  - input: ":question: What is your name"
    fields:
      - text: "Name"
        key: "name"
  - label: ":golang: Run the application"
    command: ".buildkite/scripts/run.sh"

    